### ISSUE TITLE
syntax error in export_layers.py

### ISSUE THREAD

**Issue by stevemaunsell** [kamilburda/gimp-export-layers#100]
#### What went wrong?

New install. Plugin is not detected in Win10 GIMP 2.10.32r1.

#### If you can, tell us the steps to reproduce the problem.

Running GIMP on verbose mode shows:

`Querying plug-in: 'C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\export_layers\export_layers.py'
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\export_layers\export_layers.py", line 1
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax`

The above doesn't have line breaks. The ^ is pointing to the first character in line 1 which is the <

#### Configuration

Version of Export Layers: 3.3.4

Version of GIMP: 2.10.32r1

Operating system: Win10

**Comment by kamilburda** [comment]
Try removing `Readme.html` from your `plug-ins` folder. Looks like GIMP tries to interpret this file as a plug-in.

If this works for you, I'll update the installation instructions to not copy the HTML file to `plug-ins`.

**Comment by kamilburda** [comment]
Looking more closely at the error message, I noticed that the `export_layers.py` file is inside the `export_layers` folder - the file must be outside this folder, i.e. directly under `plug-ins`.

**Comment by stevemaunsell** [comment]
Not quite. Inside the \plug-ins\export_layers\ folder is exportlayers.py file (along with several other .py files) but outside in the \plug-ins\ folder is export_layers.py. This is how the export_layers-3.3.4.zip download extracts. I noticed this on install and questioned it but the files are differentiated by the _ and it is how the download is supplied.

Also, I didn't extract the readme.html file.

**Comment by stevemaunsell** [comment]
I removed \plug-ins\export_layers\export-layers.py and no longer get the original error but now get:

'Querying plug-in: 'C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\export_layers.py'
gimp-2.10.exe: LibGimpBase-WARNING: gimp-2.10.exe: gimp_wire_read(): error'

**Comment by stevemaunsell** [comment]
Odd. I must've put it there when testing.
All good now. Reinstall of GIMP & plugin got it working.
Works great!

**Comment by kamilburda** [comment]
No problem, glad to hear it's working.
