### ISSUE TITLE
Image metadata is lost on export

### ISSUE THREAD

**Issue by Crimsonum** [kamilburda/gimp-export-layers#108]
#### What went wrong
When exporting layers as .JPG images and selecting the option to preserve the IPTC metadata, the metadata is lost in export.

#### Steps to reproduce

1. Select some images that have IPTC metadata. Open them as layers in GIMP. In my case, I'm batch converting .HEIC images to .JPG.
2. Export the layers as separate images using the Export Layers plugin.
3. Select JPG as the export format.
4. Select to save the IPTC metadata.
5. Open the exported image(s) and view the metadata.

#### Configuration

Version of Export Layers:  4.0.1

Version of GIMP: 2.10.34

Operating system: Windows 10

Procedures and constraints added in Export Layers: Use Layer Size, Layers

---

Examples:

Viewing the image metadata:
![image (2)](https://github.com/kamilburda/gimp-export-layers/assets/17765965/c4428c70-cee0-4fd7-97ca-7175745d0cba)

Selecting to preserve the metadata on export:
![image (1)](https://github.com/kamilburda/gimp-export-layers/assets/17765965/ebcb3fd8-33eb-40a5-bb2f-a7418a033606)

After export, the metadata is gone:
![image (3)](https://github.com/kamilburda/gimp-export-layers/assets/17765965/6062c648-5a68-461d-b707-b6ca14507953)

**Comment by kamilburda** [comment]
Thanks for the detailed report. I just released [4.0.2](https://github.com/kamilburda/gimp-export-layers/releases/tag/4.0.2) which should add image metadata to each exported layer.
