### ISSUE TITLE
Dialog not appearing

### ISSUE THREAD

**Issue by kubinka0505** [kamilburda/gimp-export-layers#113]
#### What went wrong?
Dialog not appearing, as in picture incl. directories config

#### Configuration

Version of Export Layers: latest

Version of GIMP: 2.10

Operating system: Windows 10

![els](https://github.com/user-attachments/assets/d7cb8b59-4289-4e06-80e2-084ba48b295a)

**Comment by kamilburda** [comment]
Hi, try moving `export_layers.py` and `export_layers` directly under `plug-ins`, i.e. the paths should be:
```
C:\Users\<username>\AppData\Roaming\GIMP\2.10\plug-ins\export_layers.py
C:\Users\<username>\AppData\Roaming\GIMP\2.10\plug-ins\export_layers
```

**Comment by kubinka0505** [comment]
> Hi, try moving `export_layers.py` and `export_layers` directly under `plug-ins`, i.e. the paths should be:
> 
> ```
> C:\Users\<username>\AppData\Roaming\GIMP\2.10\plug-ins\export_layers.py
> C:\Users\<username>\AppData\Roaming\GIMP\2.10\plug-ins\export_layers
> ```

Doesn't work either, sadly

I also noticed that I have `autocrop-linked-layers` plugin that is also not showing - I have used it before and it worked. I know this is beyond this issue subject, but is there any test plugin or setting to make them visible?

**Comment by kamilburda** [comment]
Off the top of my head, here's what you could try:

* If you reinstalled GIMP recently and you don't see `Filters -> Python-Fu -> Console`, then GIMP was not installed with Python support enabled (so no Python plug-ins would work, including the two you mentioned).
* If you did install GIMP with Python, are you able to run Python plug-ins shipped with GIMP, such as `Filters -> Decor -> Fog...`?
* Check if `Edit -> Preferences -> Folders -> Plug-ins` contains the folder `C:\Users\<username>\AppData\Roaming\GIMP\2.10\plug-ins`. If not, you must add it in order for the plug-ins to work correctly. Alternatively, you could try installing the plug-ins to one of the other locations displayed there.
* Check if there is a file called `plug-ins\export_layers\error.log`, which can also contain errors related to this plug-in during GIMP startup. If so, you can paste the contents here so I could take a look at the problem.

**Comment by kubinka0505** [comment]
>     * If you reinstalled GIMP recently and you don't see `Filters -> Python-Fu -> Console`, then GIMP was not installed with Python support enabled (so no Python plug-ins would work, including the two you mentioned).
![obraz](https://github.com/user-attachments/assets/f908cc2c-7c4a-4478-b6ee-16579f0adbe1)

>     * If you did install GIMP with Python, are you able to run Python plug-ins shipped with GIMP, such as `Filters -> Decor -> Fog...`?
![obraz](https://github.com/user-attachments/assets/5f9a7e16-644f-48b7-8d6a-011bc774c97f)

>     * Check if `Edit -> Preferences -> Folders -> Plug-ins` contains the folder `C:\Users\<username>\AppData\Roaming\GIMP\2.10\plug-ins`. If not, you must add it in order for the plug-ins to work correctly. Alternatively, you could try installing the plug-ins to one of the other locations displayed there.
![obraz](https://github.com/user-attachments/assets/8ee46dbf-27de-44d2-aba0-71234bc8ee0c)

>     * Check if there is a file called `plug-ins\export_layers\error.log`, which can also contain errors related to this plug-in during GIMP startup. If so, you can paste the contents here so I could take a look at the problem.
There is no such file.

Location is `C:\Users\Jakub\Downloads\Programs\Portable\GIMP 2`

**Comment by kamilburda** [comment]
Ah, I see this is a portable installation. Not sure why GIMP does not pick up on the `plug-ins` location under `AppData`, though. Try moving the plug-in files to `C:\Users\Jakub\Downloads\Programs\Portable\GIMP 2\lib\gimp\2.0\plug-ins.`

**Comment by kamilburda** [comment]
I see that there is no Python-Fu console available (nor do I see the Fog plug-in). This very likely means that your GIMP installation is not shipped with Python. Your best bet is to reinstall GIMP with Python plug-in support enabled. Or, if the portable installation does not provide Python as an option, then you may have to download the official (non-portable) GIMP installation from gimp.org.

**Comment by kubinka0505** [comment]
Reinstalled GIMP and works. Shame that I can't use it with portable version...
