### ISSUE TITLE
Plugin does not load (OSX)

### ISSUE THREAD

**Issue by pmenke** [kamilburda/gimp-export-layers#21]
Hello, I am unable to use the plugin since it cannot be loaded when Gimp starts. The error messages (from running GIMP from terminal with `--id --verbose` options) are as follows:

```
Gimp
/Applications/Gimp.app/Contents/MacOS
Ein Nachrichtenbus kann nicht ohne eine Rechner-Kennung erzeugt werden:/var/lib/dbus/machine-id oder /etc/machine-id konnte nicht geladen werden: Datei »/var/lib/dbus/machine-id« konnte nicht geöffnet werden: No such file or directory
GIMP-Fehler: Unable to run plug-in "export_layers"
(/Applications/Gimp.app/Contents/Resources/lib/gimp/2.0/plug-ins/export_layers)

Kindprozess »/Applications/Gimp.app/Contents/Resources/lib/gimp/2.0/plug-ins/export_layers« konnte nicht ausgeführt werden (Permission denied)
```

Sorry, it's in German due to my machine's setup, but the last line says 'child process could not be executed (Permission denied).'.

I already tried to find solutions in some of the other issues, namely, #12, #14, #15 - but I could not get it to work even by following the instructions there.

Specifically, I checked the permissions of plugin files and folders (both scripts and folders are executable), and I also made sure that a current version of python is used by changing the `pygimp.interp` file, as suggested.

Still, the above error occurs, and I am not sure how helpful and accurate the final message "Permission denied" is. 

Inside GIMP, the menu items of the plugin are there, but when I select them, an icon appears (looks like a writing quill) for just half a second (as if it starts), and then disappears. I have no log files associated with export_layers plugin in my folders.

I am using GIMP 2.8.10, and version 2.2.2 of the export_layers plugin (installed from the ZIP file), under OSX Yosemite (10.10.1). 

Thanks in advance!

**Comment by khalim19** [comment]
As noted in a [related comment](https://github.com/khalim19/gimp-plugin-export-layers/issues/12#issuecomment-68439114), GIMP tries to execute everything in the `plug-ins` directory, including subdirectories. The error message most likely doesn't relate to the problem you're having.

Since the menu items showed up, the plug-in should be installed correctly.

Open up `export_layers/pygimplib/constants.py` and change the line

	DEBUG = False

to

	DEBUG = True

A log file named `export_layers_error.log` should appear in the `export_layers/pygimplib` directory. If the file is there, paste its contents here. Perhaps even `export_layers.log` could be of use - if it exists, paste its contents here as well.

Also, to be absolutely sure, are you using Python 2.7.x?

**Comment by pmenke** [comment]
Hello, thanks for your time! I followed your instructions. Now, both `export_layers.log` and `export_layers_error.log` have been created, but they are both empty (both have a length of 0). 

But another thing changed (as far as I can tell) after enabling Debug: When I select one of the menu items, a segmentation fault occurs:
```
/Applications/Gimp.app/Contents/Resources/lib/gimp/2.0/plug-ins/export_layers: fatal error: Segmentation fault: 11
```
(This is from the attempt where the plugin is installed in the global Gimp folder. I also tried to use the Gimp plugin folder inside my home directory, but the effects are identical). 

As to the Python version question, I did everything I can to make Gimp use Python 2.7. The default interpreter is 2.7.6, and as I mentioned, I changed `pygimp.interp` according to the description mentioned above in order to use a different Python than the default one. ~~However, I do not know for sure whether Gimp really uses 2.7. I searched the Gimp GUI for a way to find out the Python version used, but couldn't find any information on that.~~ 

Update: I added a line to your script that prints the Python version, and it says 
```2.7.6 (default, Sep  9 2014, 15:04:36)```
(probably not the most recent one, but at least it appears that Gimp is really using 2.7.6).

**Comment by khalim19** [comment]
Thanks, the Python version is correct.

I have no idea why the segmentation fault appears. There are a few more things you could try to isolate the issue.

Open up an image in GIMP, open the Python-Fu console (Filters -> Python-Fu -> Console...) and run

	pdb.plug_in_export_layers_to(gimp.image_list()[0])

If the console throws an error (it will probably display "Execution error"), check the log files. In case it works, the layer(s) should be exported to the Documents directory in your home directory.

If the log files are empty, try [version 2.1](https://github.com/khalim19/gimp-plugin-export-layers/releases/tag/2.1) of the plug-in instead. If that doesn't work, try [version 2.0](https://github.com/khalim19/gimp-plugin-export-layers/releases/tag/2.0) - note that you'll need to set the executable permission on `export_layers.py`.

If even 2.0 doesn't work, there might be some Python modules missing (although I doubt it). Open up the Python-Fu console, paste the following lines to the console and see if you get an `ImportError`:

	import gimp
	import gimpenums
	import gimpui
	import gimpshelf
	import json
	import webbrowser
	from collections import defaultdict
	from collections import OrderedDict
	from collections import namedtuple
	from contextlib import contextmanager
	import errno
	import traceback
	import gtk
	import gobject
	import pango

Also, have you tried other GIMP Python scripts (such as [Layer Effects](http://registry.gimp.org/node/186)) to see if they work?

**Comment by imdevin567** [comment]
I have this issue as well. The suggestion above to type the command into Python-Fu worked for me, however.

**Comment by khalim19** [comment]
@imdevin567: Many thanks. I suspect there is a problem with the GUI in my plug-in. Could you try the following command to the Python-Fu console? It's the same command as the one above, with the difference that it now displays the GUI:

    pdb.plug_in_export_layers_to(gimp.image_list()[0], run_mode=0)

Could you also try out the import commands above in the Python-Fu console? That way, I could eliminate the missing modules as the potential problem.

**Comment by pmenke** [comment]
Hello, here are my results:

1. The call in the console without the GUI runs without any problems.
2. The library calls (`import gimp`, etc.) all succeed without any error.
3. When I follow your last suggestion and run the console call with the GUI display, no GUI is shown, and the following debugging output appears:
````
Traceback (most recent call last):
  File "<input>", line 1, in <module>
RuntimeError: Prozedur »plug-in-export-layers-to« hat sich ohne Rückgabewerte beendet
````
The German error text (sorry, I don't know how to switch that to English) means: the procedure »plug-in-export-layers-to« has terminated without giving any return value. 

There is, however, nothing written to the log files during this test.

**Comment by khalim19** [comment]
Thanks for the information. It looks like the problem lies in the GUI.

[I made a patch](https://gist.github.com/khalim19/283b21e0e293a9e5750e) to remove a non-essential part of the GUI. Could you try the command with the GUI display again to see if it works for you now?

Copy the `gui_plugin.py` file to `plug-ins/export_layers` (and overwrite if asked).

**Comment by elbyron** [comment]
Hi, I'm not sure if this is related or not, but I'm also unable to get the GUI to load. I'm running Windows 7 64-bit, with fresh install of Gimp 2.8.14 direct from the Gimp site. That includes python 2.7.5.  When I try to use the "Export Layers..." or "Export Layers to" menu options, it opens an empty dialog window titled "Export Layers" and then immediately pops up a message saying "pythonw.exe has stopped working". 
The results of my testing using the above instructions are a little different:
- with debug turned on, my log file shows warnings about failures to load icons
- calling pdb.plug_in_export_layers_to with no GUI works
- calling pdb.plug_in_export_layers_to with GUI does absolutely nothing... no console error, no empty dialog, no error popup, and nothing in the log files.
- replacing gui_plugin.py with the patched file did not seem to change anything, same errors occur.

Here's the contents of my log files showing the icon errors:
=============================================================================
Export Layers
2015-02-20 16:18:32.286000

C:\Users\elbyron\.gimp-2.8\plug-ins\export_layers\gui_plugin.py:209: GtkWarning: Error loading theme icon 'edit-find' for stock: Failed to load icon
  self.folder_chooser = gtk.FileChooserWidget(action=gtk.FILE_CHOOSER_ACTION_SELECT_FOLDER)

C:\Users\elbyron\.gimp-2.8\plug-ins\export_layers\gui_plugin.py:209: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
  self.folder_chooser = gtk.FileChooserWidget(action=gtk.FILE_CHOOSER_ACTION_SELECT_FOLDER)
C:\Users\elbyron\.gimp-2.8\plug-ins\export_layers\gui_plugin.py:209: GtkWarning: Error loading theme icon 'text-x-generic' for stock: Failed to load icon
  self.folder_chooser = gtk.FileChooserWidget(action=gtk.FILE_CHOOSER_ACTION_SELECT_FOLDER)
C:\Users\elbyron\.gimp-2.8\plug-ins\export_layers\gui_plugin.py:336: GtkWarning: Error loading theme icon 'edit-find' for stock: Failed to load icon
  self.dialog.vbox.pack_start(self.folder_chooser, padding=5)
C:\Users\elbyron\.gimp-2.8\plug-ins\export_layers\gui_plugin.py:336: GtkWarning: render_fallback_image: assertion 'pixbuf != NULL' failed
  self.dialog.vbox.pack_start(self.folder_chooser, padding=5)
C:\Users\elbyron\.gimp-2.8\plug-ins\export_layers\gui_plugin.py:336: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
  self.dialog.vbox.pack_start(self.folder_chooser, padding=5)
C:\Users\elbyron\.gimp-2.8\plug-ins\export_layers\gui_plugin.py:336: GtkWarning: Error loading theme icon 'text-x-generic' for stock: Failed to load icon
  self.dialog.vbox.pack_start(self.folder_chooser, padding=5)
C:\Users\elbyron\.gimp-2.8\plug-ins\export_layers\gui_plugin.py:370: GtkWarning: Error loading theme icon 'gtk-edit' for stock: Failed to load icon
  self.dialog.show()
C:\Users\elbyron\.gimp-2.8\plug-ins\export_layers\gui_plugin.py:370: GtkWarning: render_fallback_image: assertion 'pixbuf != NULL' failed
  self.dialog.show()
C:\Users\elbyron\.gimp-2.8\plug-ins\export_layers\gui_plugin.py:370: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
  self.dialog.show()
C:\Users\elbyron\.gimp-2.8\plug-ins\export_layers\gui_plugin.py:370: GtkWarning: Error loading theme icon 'folder' for stock: Failed to load icon
  self.dialog.show()
C:\Users\elbyron\.gimp-2.8\plug-ins\export_layers\gui_plugin.py:370: GtkWarning: Error loading theme icon 'image-missing' for stock: Failed to load icon
  self.dialog.show()

**Comment by khalim19** [comment]
For those of you who experience crashes when exporting layers or clicking the Advanced Settings button, try reinstalling GIMP. I got a mail from a user who had the same issue, and reinstalling GIMP fixed it for him.

**Comment by kamilburda** [comment]
Closing this due to the issue being stale and referring to outdated versions of the plug-in.
