### ISSUE TITLE
Special option for PDF: Export layers to a single multi-page PDF

### ISSUE THREAD

**Issue by khalim19** [kamilburda/gimp-export-layers#38]
While GIMP has a built-in procedure named `file-pdf-save-multi`, [it doesn't work in the non-interactive run mode](http://www.gimpchat.com/viewtopic.php?f=9&t=12418) and is probably deprecated by now.

There are scripts that do provide multi-page PDF export (utilizing ImageMagick):
- http://registry.gimp.org/node/25677
- http://registry.gimp.org/node/27987

To promote reuse, we could wrap one of the above scripts (not including it in the plug-in, but linking to it so that users can download it) combined with this plug-in's features to improve the multi-page PDF export.

If it turns out we can't use the above script(s), we'll need to make our own solution, using one of [available Python PDF tools/libraries](https://www.binpress.com/tutorial/manipulating-pdfs-with-python/167), such as [PyPDF2](https://github.com/mstamy2/PyPDF2).

This setting should be off by default and should only appear when the user types/chooses the "pdf" file extension.

**Comment by prokoudine** [comment]
GIMP 2.10.x ships with this feature. I guess you can close this feature request :)

**Comment by khalim19** [comment]
Great! It's definitely a huge relief not to have to deal with workarounds mentioned in the OP.

On a second thought, though, we could still make the plug-in apply additional operations like background layers, include layers within groups as individual pages , etc. - simply leveraging all the plug-in settings. Thus, I'll leave this open for now, although this would require introducing non-trivial changes to the code since now each layer is processed and saved separately, while a multi-page PDF would require saving to be performed only once.

**Comment by kamilburda** [comment]
Multi-layer export, including multi-page PDF, is now supported in 4.0. While multi-page PDF export is already possible in GIMP, this plug-in also allows applying procedures before the export (e.g. background insertion on each page).
