### ISSUE TITLE
Let users add custom procedures and constraints

### ISSUE THREAD

**Issue by khalim19** [kamilburda/gimp-export-layers#39]
Allow users to customize export easily by adding custom operations - GIMP PDB procedures (adjust brightness, scale, ...) or constraints (only chained layers, only layers below given opacity, ...). Users should also be able to adjust the parameters of each operation.

Custom operations should also be invoked if the plug-in is called in non-interactive mode, with the option to disable them.

As a side effect, some advanced features (Ignore layer modes, Export only layers matching file extension, ...) ought to be removed from the UI to reduce clutter in the UI (leading to UI redesign dealt with in issue #37). Instead, users should be able to add these features back as custom operations/constraints.

**Comment by kamilburda** [comment]
Custom procedures are implemented. Custom constraints will be implemented in [Batcher](https://github.com/kamilburda/batcher).
