### ISSUE TITLE
A few inconsistencies and a request

### ISSUE THREAD

**Issue by ZeroComfort** [kamilburda/gimp-export-layers#48]
@khalim19 Great plugin, but I found the following inconsistencies (3.0-RC1):
- Filter "Include layers" unchecked state is not saved.
- With filter "Include layers" unchecked and "Include layer groups" checked, it will still export all layers individually instead of merging the groups (expected behavior).

For now using filter "Only layers selected in preview" checked and selecting only the layer groups is a viable workaround.

A request:
- An "Only top-level layer groups" filter.

**Comment by khalim19** [comment]
"Include layers" is checked by default. If you uncheck it and save settings, the unckecked state should be preserved.

Unchecking "Include layers" and checking "Include layer groups" should export all layer groups. if you also check "Only top-level layers", the plug-in should export only top-level layer groups (as indicated in the preview).

You may want to try the latest revision from the repository and see if it works as intended, as I made a few adjustments to how the filters work.

**Comment by kamilburda** [comment]
This is now more intuitive as of 4.0 - uncheck `Layers`, check `Layer groups` and check `Top-level` constraints.
