### ISSUE TITLE
Python plugin error on gimp 2.10.3 on macOS

### ISSUE THREAD

**Issue by douira** [kamilburda/gimp-export-layers#60]
#### What went wrong?
`Traceback (most recent call last):  
File "/Users/douira/Library/Application Support/GIMP/2.10/plug-ins/export_layers/pygimplib/pggui_entries.py", line 69, in _on_entry_changed  
    if self._entry.get_realized():  
AttributeError: 'FileExtensionEntry' object has no attribute 'get_realized'`

#### If you can, tell us the steps to reproduce the problem.
Clicked on export layers in the menu.

#### Configuration

Version of Export Layers: (latest at the time) 3.2.1

Version of GIMP: 2.10.3 from "about gimp" and 2.10.2 on download page, idk why there is a difference

Operating system: macOS 10.13.5 (High Sierra)

Downloaded from (https://www.partha.com/) https://www.partha.com/downloads/McGimp-2.10-std.app.zip

**Comment by khalim19** [comment]
This is quite strange, it looks like it's a problem with GTK (the GUI framework used in GIMP) rather than the plug-in itself. Either way, I'll take a closer look at this in a few days.

In the meantime, have you tried the official 2.10.4 build?

**Comment by douira** [comment]
Thanks for looking into the issue! I can't try anything newer than my current one yet because I have to rely on third-party versions like the one I'm using for it to work on macOS as there is no official build.

**Comment by khalim19** [comment]
There appears to be a macOS build on the [GIMP downloads](https://www.gimp.org/downloads/) page (labeled as OS X).

**Comment by douira** [comment]
oh wow, ok I didn't see that. I guess the other build was just ahead of the official one then. I'll try the plugin on 2.10.4 soon then.

**Comment by khalim19** [comment]
I finally got around to testing this out, here are my findings:
* The official build from the GIMP page works properly.
* The build from Partha's Place fails because it uses PyGTK 2.17, while my plug-in requires a later version (very likely 2.22 or above).

If possible, use the download from the GIMP page. While I could work around this issue to make the plug-in work on the Partha's build, I fear it would introduce UI bugs and maintenance difficulties because of backward compatibility.

**Comment by douira** [comment]
Okay thanks for testing it out, I've been busy lately. Thanks for the info! I'll use the official build when I want to use this plugin then.

**Comment by kamilburda** [comment]
Closing this issue due to being stale.
