### ISSUE TITLE
Option to scale down layers before exporting

### ISSUE THREAD

**Issue by KernelLeak** [kamilburda/gimp-export-layers#61]
I just successfully used your plugin to export a slew of selfmade Windows icons for use with Foobar2000 (and thanks to your plugin didn't have to export each one separately), but there's one thing that I thought could be useful:

I drew several icons at 256x256 pixels to get them to look smooth, but Foobar2000 expects 16x16 pixel icons for it's toolbar. I downscaled the whole image to one 16th before invoking your plugin, but that meant that I had to arrange every icon on a 16 pixel boundary so that none of the icons ended up "between pixels" due to downscaling, and it's an extra step that has to be done every time before exporting.

If the plugin had an option to downscale (or maybe just scale) the exported layers by a custom percentage before saving placement of the layers probably wouldn't have mattered (assuming the layer gets transposed to 0,0 before saving).

Also, I'm pretty sure there are other usecases where you work at a higher resolution but want the final exported files scaled down.

Just my two cents... :)

**Comment by khalim19** [comment]
Once custom operations are implemented in the plug-in, you'll be able to apply any procedure on the layers, including scaling. No word on when I get this done, though, probably in a few weeks.

**Comment by KernelLeak** [comment]
Well, that's a lot more than I was thinking of asking for in a feature request - but of course **that solution** is going to make this possible in one fell swoop... :)

**Comment by khalim19** [comment]
This is doable as of version 3.3:

1. Go to Settings -> Show More Settings
2. Click "Add Procedure..."
3. Look up `gimp-layer-scale` or `gimp-layer-scale-full`, add the procedure and set the values as needed.
4. If you want to use the layer size, move the scale procedure before "Use Layer Size" (by dragging and dropping).

**Comment by kamilburda** [comment]
A custom Scale procedure was added to Export Layers in version 4.1, which allows scaling down layers based on % of image/layer width/height beside pixels.
