### ISSUE TITLE
Export Layers only visible in english settings

### ISSUE THREAD

**Issue by JerryInc89** [kamilburda/gimp-export-layers#64]
#### If you can, tell us the steps to reproduce the problem.
Installed the plugin several times but it only showed up setting the interface to english

#### Configuration
German language (auto-detected)
Version of Export Layers: 
3.2.10
Version of GIMP: 
2.10
Operating system: 
Windows 7

**Comment by khalim19** [comment]
Sorry, this plug-in does not currently support German language. Contributors are welcome to provide German translation for the plug-in as per the [guidelines](https://github.com/khalim19/gimp-plugin-export-layers/blob/master/TRANSLATIONS.md).

**Comment by kamilburda** [comment]
German translation is available now in the plug-in, but due to significant changes in 4.0, some translatable strings are missing. Contributions are welcome. :)
