### ISSUE TITLE
Editing operations: Elements of array parameters are displayed with incorrect height when pressing Reset and then Cancel

### ISSUE THREAD

**Issue by khalim19** [kamilburda/gimp-export-layers#67]
Steps to reproduce:
1. Add a custom procedure containing an array parameter, e.g. `gimp-paintbrush`.
2. Set the size of the array to a non-zero value, e.g. 6.
3. Close the dialog.
4. Edit the procedure (open the dialog again).
5. Press Reset.
6. Press Cancel.
7. Edit the procedure again.

Result: Each element in the array has a height of 1 pixel.

Workaround: Edit the procedure and press Cancel again.

**Comment by kamilburda** [comment]
Fixed in 4.0.
