### ISSUE TITLE
Clicking on popup contents spawned by "More" button freezes plug-in

### ISSUE THREAD

**Issue by khalim19** [kamilburda/gimp-export-layers#70]
#### What went wrong?

Plug-in dialog becomes unresponsive if the user clicked inside the popup displayed by clicking the "More" button for long in-dialog messages.

#### If you can, tell us the steps to reproduce the problem.

1. Add "\ " to the file extension at the end to display an error message with "More" button.
2. Click the "More" button.
3. Click anywhere on the displayed popup.

#### Configuration

Version of Export Layers: 3.3

Version of GIMP: 2.8+

Operating system: Linux and macOS

**Comment by kamilburda** [comment]
"Fixed" by replacing the popup with a tooltip.
