### ISSUE TITLE
Does not install after fresh GIMP installation with Python scripting enabled

### ISSUE THREAD

**Issue by notmutiny** [kamilburda/gimp-export-layers#78]
#### What went wrong?
"It appears that your GIMP installation does not support Python scripting. Please install GIMP with enabled support for Python scripting before proceeding."

#### If you can, tell us the steps to reproduce the problem.
1. Clean install GIMP **with Python scripting enabled** on Windows 10
2. Attempt to install this via the provided executable

#### Configuration

Version of Export Layers: 3.3.1

Version of GIMP: 2.10.12

Operating system: Windows 10 x64

**Comment by notmutiny** [comment]
I checked your installer code and this path is met within my GIMP directory:
```
possiblePythonDirpaths.Add(GimpDirpath + '\lib\python2.7');
```
Not sure what's up with your code but my folder hierarchy is correct.

**Comment by notmutiny** [comment]
I quickly realized after sweeping the installer code that it's not asking for the GIMP executable but the GIMP folder itself, so after bumping up the paths it installer throws "Internal error: An attempt was made to expand the app constant before it was initialized." Love it.

**Comment by notmutiny** [comment]
After clicking "back" for a few slides in the installer and repeating the installation in the same installer instance it seems to work. Problem solved but not fixed so I'm not closing it. Installer has some issues,

**Comment by animodium** [comment]
Thanks beaucoup for this. Saved my life.

**Comment by zTaaso** [comment]
@notmutiny You are my hero. Thanks a lot!

**Comment by khalim19** [comment]
Thanks for reporting this issue. In the end, though, I decided to scrap the Windows installer (something that I'd been contemplating from the very start actually) for two reasons:
* The installer (the .exe file) is not digitally signed and I'd rather not have Windows display a warning message about an unverified program. As I understand it, signing the installer would be very costly.
* With the development of GIMP 3.0, a plug-in manager is expected to be a built-in feature of GIMP, so the installer won't be necessary anymore.

I'll keep this issue open just in case the Windows installer will be brought back.

**Comment by kamilburda** [comment]
Closing this as the Windows installer will not be brought back in the near future.
