### ISSUE TITLE
A request for new options.

### ISSUE THREAD

**Issue by MareroQ-MrQ** [kamilburda/gimp-export-layers#81]
Thank you so much for the excellent plugin.
I'm using Gimp 2.10.14 (from gimp.org) on Windowe10 64bit.
I use your plugin interchangeably with BIMP - so comparing the action: I have a question and a request - is it possible to add the option:
- load settings from file?
- apply to layers (or open exported layers)?

An example (very good solution) comes from PaintDotNet ......
https://forums.getpaint.net/topic/6091-scriptlab/
![Pdn ScriptLab](https://user-images.githubusercontent.com/58288753/70002136-6d6a9780-155f-11ea-949e-e1144b622af6.png)

**Comment by khalim19** [comment]
Loading settings from file shouldn't be too difficult to implement. I'll add this feature to 3.4.

I am not sure if I understand the second feature request - is it applying filters (effects) on layers without exporting them, or batch-processing files (basically what BIMP does)?

The former is one of my ultimate goals. However, given how intertwined the export is with the code base, separating the export will definitely not be easy.

The latter should also be doable, but, as indicated, the plug-in code requires substantial refactoring before this is possible. Beside Real Life™ and other projects, this is going to take a long time, I'm afraid.

**Comment by MareroQ-MrQ** [comment]
I would love the option of opening for Export-Layers layer after applying additional procedures.
My attempt to resolve this issue is here (but it would be better without my addition)
http://gimpchat.com/viewtopic.php?f=9&t=17874&p=245620#p245620

**Comment by kamilburda** [comment]
Version 4.0 now supports batch-editing layers without exporting them and exporting/importing settings. I suppose this can be closed now. ☺️

**Comment by MareroQ-MrQ** [comment]
Thank You very much for the solutions introduced and the constant development of an excellent plugin. 
In Gimp-2.10.34 (Win10_64bit) when trying to write (Export Settings) as JSON I get this error:
<class 'export_layers.pygimplib.setting.settings.IntSetting'> is not JSON serializable.

Export/import as *.pkl works as expected.

**Comment by kamilburda** [comment]
I tried exporting settings to JSON with PDB procedures containing an integer argument (since the error message indicates the problem is with integer arguments), but I cannot reproduce the problem.

If possible:

* Can you provide the entire error message (if there is more than that one line)?
* Can you list the procedures and constraints used?
* Can you provide the saved .pkl file? I might then be able to reproduce this on my end. 

Did you by any chance download the source code before 4.0 was released? I had made some substantial changes to the format of plug-in settings between the releases which could possibly cause some unintended side effects (notably some obsolete settings not being removed or updated).

**Comment by MareroQ-MrQ** [comment]
Version Export Layers: latest release (4.0, August 06, 2023).
I confirm that the problem with export to JSON occurs only for some procedures (when pkl handles it).
No other information about the problem (I will add that in such cases it creates a 0 b json file).

![EL-4](https://github.com/kamilburda/gimp-export-layers/assets/58288753/82b0ebed-0efa-4a98-a8b6-933a194da4c6)

Sample file in attachment.
[test_pkl.zip](https://github.com/kamilburda/gimp-export-layers/files/12385174/test_pkl.zip)

**Comment by kamilburda** [comment]
Thank you, I just released 4.0.1 that should fix this. You should now be able to export setting as a JSON file.

**Comment by kamilburda** [comment]
Thank you, I just released 4.0.1 that should fix this. You should now be able to export setting as a JSON file.

**Comment by MareroQ-MrQ** [comment]
Many thanks for solving the problem in no time (although a single export format would have sufficed).
BIMP will now be completely unused.
Topic to be closed.

**Comment by kamilburda** [comment]
I agree that one format should suffice, specifically the JSON format as it could possibly be used for automation in the slightest case that someone would e.g. want to automatically create several modifications of the saved file and export with a different configuration every time.

The pickle file format also acts as a fallback in case the [`json` module is missing for some uncommon GIMP installations](https://github.com/kamilburda/gimp-export-layers/issues/19#issuecomment-67774232).
