### ISSUE TITLE
Missing "Do not strip file extension" option.

### ISSUE THREAD

**Issue by Siwy160** [kamilburda/gimp-export-layers#84]
#### What went wrong?
Script always removes "file extension" from layer name.
In the past, there was an option called "Do not strip file extension" i believe.

#### If you can, tell us the steps to reproduce the problem.
1. Create layer called "test.9"
2. Export layers using plugin.

Noticed:
Output file is named "test.png"

Expected:
Ofutput file named: "test.9.png"

Note: That "9." means its nine-path, not really extension.
Note2: When i check "Use file extension in layer name" it tries export as "test.9" which is also incorrect.

#### Configuration

Version of Export Layers: 3.3.1

Version of GIMP: 2.10.18

Operating system: Windows 10

**Comment by khalim19** [comment]
I believe this is the same question as I described here:
https://github.com/khalim19/gimp-plugin-export-layers/issues/93#issuecomment-1250062435

In short, this option was moved to the layer name text field next to "Save as:". Typing `[layer name, %e]` should be equivalent to "do not strip file extension from the layer name".

**Comment by kamilburda** [comment]
Closing this as this was resolved.
