### ISSUE TITLE
Removing "#x" from end of layer group names

### ISSUE THREAD

**Issue by stigzler** [kamilburda/gimp-export-layers#87]
Hi. Firstly, I love this plugin - it's the mutt's nuts. 

Secondly, I looked through "Customising Layer Names" but couldn't find an answer. 

I need a way to remove the "#1" or "#2" from the end of Layer and Layer Group names. Sometimes, I will want two images named the same in export, but you can't have the same Layer/Group name in GIMP. For example, I might want two images called "cats.png" in different folders from the export. As it sits in GIMP, I get:

Domestic Animals
--cats
Zoo Animals
--cats #1

How do I remove the auto generated "#x" from the end on export?

**Comment by khalim19** [comment]
These suffixes can't be removed directly. As a workaround, you can type `cats` as a filename (when you click on Show More Settings). If you also want to include the layer groups, you can specify e.g. `[layer path]-cats`, which will produce filenames `Domestic Animals-cats.png` and `Zoo Animals-cats.png`.

**Comment by khalim19** [comment]
This is now possible via the new `[replace]` field in the filename pattern in 3.3.2. Copy and paste the following text in the filename pattern: `[replace, [layer name], [ copy(?: #[[0-9]]+)*$], [] ]`

It looks a little cryptic, but it should get the job done properly. You can, of course, use a different field than `[layer name]` if needed.

**Comment by Stechmuck** [comment]
Very nice feature. Thank you!

But is it also possible to rename layergroup names?
Domestic Animals

- cats
- 

--cats
--thumbs

----cats #1
Zoo Animals
--cats #2
--thumbs #1
----cats #3

**Comment by kamilburda** [comment]
Yikes, I completely forgot that layer group names are excluded from renaming. This is currently not possible at the moment, but I'll make it possible in the next version.

**Comment by kamilburda** [comment]
Renaming layer groups is now possible in 3.3.5. Add the `Rename` custom procedure and check `Rename layer groups`.

**Comment by Stechmuck** [comment]
Works great. Thanks very much.
