### ISSUE TITLE
Add support for Python3

### ISSUE THREAD

**Issue by gjvnq** [kamilburda/gimp-export-layers#91]
I have been able to make this plugin work on Python3 by making only the following 3 changes:

```
diff -a /usr/lib/gimp/2.0/plug-ins/export_layers/pygimplib/__init__.py /home/user/.config/GIMP/2.10/plug-ins/export_layers/pygimplib/__init__.py
146c146
<   gettext.install(config.DOMAIN_NAME, config.LOCALE_DIRPATH, unicode=True)
---
>   gettext.install(config.DOMAIN_NAME, config.LOCALE_DIRPATH)
diff -a /usr/lib/gimp/2.0/plug-ins/export_layers/pygimplib/pglogging.py /home/user/.config/GIMP/2.10/plug-ins/export_layers/pygimplib/pglogging.py
34d33
< str = unicode
diff -a /usr/lib/gimp/2.0/plug-ins/export_layers/pygimplib/_pgpath_dirs.py /home/user/.config/GIMP/2.10/plug-ins/export_layers/pygimplib/_pgpath_dirs.py
26d25
< str = unicode
```

I think it can be easy to support both Python2 and Python3 by adding a simple version check on those three changes lines.

**Comment by SirYaro** [comment]
It really did improve things a bit but in my case there are still some errors left:

```
Traceback (most recent call last):
  File "/home/yaro/.config/GIMP/2.10/plug-ins/export_layers.py", line 41, in <module>
    import gimpenums
ModuleNotFoundError: No module named 'gimpenums'
gimp: LibGimpBase-WARNING: gimp: gimp_wire_read(): error

```

And surprisingly there is very little about gimpenums on the google...

**Comment by gjvnq** [comment]
On Manjaro Linux, I solved this problem by installing ```aur/python2-gimp```

**Comment by SirYaro** [comment]
@gjvnq I did the same with:
`sudo dpkg -i gimp-python_2.10.8-2_amd64.deb `
but it did not help too much. It only changed err msg to `undefined symbol`  (shown above).

**Comment by desmarty** [comment]
(Sorry to the developer) As this plugin is out dated or may be it is inactive on current issues, I made scripts for the same purpose. Please find it in [Gimp Scripts - Export layers](https://github.com/desmarty/gimp_script). (This is an essential part of gimp. So I had to develop it by myself. It is a script, so it may not be broken in future releases of gimp. I am working on other essential modules for gimp too. Hope it is helpful to someone. Thank you and again sorry to this developer as i am approximately promoting my repository here)

**Comment by SirYaro** [comment]
@desmarty, for a split second I was hoping you forked and rewrote khalim19's plugin to python3... :)

**Comment by desmarty** [comment]
> @desmarty, for a split second I was hoping you forked and rewrote khalim19's plugin to python3... :)

I tried to re-write the same plugin for more than 5 days. But I found that remaking is easier and faster. The whole script now fits in less than 200 lines of code.

**Comment by SirYaro** [comment]
> @SirYaro, I tried to re-write the same plugin for more than 5 days. But I found that re-making it from the scratch is easier and faster. The whole script now fits in less than 200 lines of code.
I know it's not easy. Otherwise, I'd probably try to do it myself :P 
Anyway, I checked your work, and it looks like a step in the right direction. Unfortunately, right now it can replace khalim's work only in the simplest applications. :( 
Tbh I don't remember if I ever had to just export all layers without any constrains.
Features that khalim called procedures and constraints are the one that makes his script so valuable (to me). They were/are far from being perfect, but I always could walk around its limitations and saved dozens of hours every project I made.

**Comment by desmarty** [comment]
@SirYaro Wow!! People are doing a lot of things in Gimp. :D I am purely naive then. I ll definitely update my work and include all of the features that this plugin had. Sorry, my work is not helpful for you now.

**Comment by khalim19** [comment]
I do plan to port this plug-in to GIMP 2.99 (which uses Python 3), although this will definitely take a non-trivial amount of time due to radical changes to the GIMP API, not to mention changes in GTK 3.0 (this plug-in heavily relies on custom GTK widgets, yikes!) and Python 3 compared to their 2.x counterparts.

**Comment by SirYaro** [comment]
OMG @khalim19 ! You have no idea how good to see you are alive and kicking! :) I tried to find a way to contact you, but I was unable to find any ctx details... :( I'd be grateful if you provide my with your email or sth..

If you need any help (that I am able to provide), I'm here for you. Unfortunately, I dislike python with every fiber of my being, so I'm afraid I won't be very useful...
Anyway, this plugin is a killer feature for me and I already make a lot of workarounds to keep it functional...

**Comment by khalim19** [comment]
@SirYaro Thank you for enjoying using the plug-in. Honestly, virtually all of the work on this plug-in involves working with Python one way or another. :)

Since you mentioned you devised some workarounds, you can open new GitHub issues with feature requests, I'm happy to hear suggestions.

**Comment by st4rl1ght1337** [comment]
I'm having the str = unicode not defined issue myself. Did the plugin switch to python 3? Python 2.7 reached end of life three years ago

**Comment by kamilburda** [comment]
This plug-in is currently working on GIMP 2.8 or 2.10, both of which use Python 2.7. It won't work in Python 3, not only because of the undefined `unicode` attribute, but also because the GIMP 2 API does not support it.

I plan to port this plug-in to GIMP 2.99, which uses Python 3, after I release a new version.

**Comment by kamilburda** [comment]
Export Layers has been ported to GIMP 2.99.16 (a development version as a precursor to the upcoming GIMP 3.0), which uses Python 3:
https://github.com/kamilburda/batcher

The plug-in is now named Batcher as I expect to add more features and make it more generic.

**Comment by xanda-escuyer** [comment]
> Export Layers has been ported to GIMP 2.99.16 (a development version as a precursor to the upcoming GIMP 3.0), which uses Python 3: https://github.com/kamilburda/batcher

Is there any advice please for those who are unable to acquire python2 and have a package manager install of gimp?

**Comment by kamilburda** [comment]
Assuming you use Ubuntu or one of its variants (e.g. Kubuntu), I found a [guide applicable for Ubuntu 20.04](https://www.gimp-forum.net/Thread-resynthesizer-gimp-python-Linux-ubuntu-20-04-all-files-to-install). It appears this fails for later versions of Ubuntu such as 22.04, though.

Other than that, I'm afraid I won't be of much help as I'm not well-versed with the intricacies of package managers.

Using an AppImage or flatpak GIMP installer is probably your best bet. The official GIMP site provides a flatpak. A custom-made AppImage for Ubuntu 22.04 is available [here](https://github.com/TasMania17/Gimp-Appimages-Made-From-Debs/releases/tag/Gimp-Python2-AppImage-Launchers-for-Linux/).
